[build]
  command = "echo 'hi'"
  publish = "demo/publishDir"

[[plugins]]
  package = "./index.js"
  [plugins.inputs]
    # required configs, customize as needed
    dirToScan = "/posts" # a subfolder to scan. "/" to scan all
    authorName = "swyx"
    site_url = "https://swyx.io"
    feed_url = "https://swyx.io/rss.xml"
    title = "swyx RSS Feed"
    rssDescription = "swyx.io RSS Feed"
    categories = ['Technology', 'JAMstack', 'Web Development']